### ISSUE TITLE
Connect DPM to PI

### ISSUE THREAD

**Issue by toessfrosch** [aloishockenschlohe/diy-smart-solarplant#1]
Danke für deine Arbeit.
Wie genau hast du das DPM an den PI angeschlossen? 
Gibt es einen Schaltplan?

Thank you for your work.
How exactly did you connect the DPM to the PI? 
Is there a circuit diagram?

**Comment by aloishockenschlohe** [comment]
Hi! :-)

Die Kommunikation zwischen dem DPM86-Netzteil und dem Raspi erfolgt über ein verdrilltes Kabel mit zwei Adern (Klingeldraht) und dem Protokoll RS485. Dazu wird dem Raspi ein entsprechender USB-Adapter spendiert (ca. € 2 bis € 5, zum Beispiel hier zu finden: https://eckstein-shop.de/QITAUSBRS485KonverterBusAdapterSeriellSchnittstelleRaspberryPi?googlede=1&ws_oss_lieferland=DE).

Vermutlich ginge es auch über die GPIO-Leiste des Raspberry, aber ich das habe ich nicht versucht.

---

Hi! :-)

The communication between the DPM86 power supply and the Raspi takes place via a twisted cable with two wires (bell wire), using the RS485 protocol. For this purpose, the Raspi is equipped with a corresponding USB adapter (approx. € 2 to € 5, to be found here, for example: https://eckstein-shop.de/QITAUSBRS485KonverterBusAdapterSeriellSchnittstelleRaspberryPi?googlede=1&ws_oss_lieferland=DE).

Presumably it would also work via the GPIO bar of the Raspberry, but I have not tried that.

**Comment by aloishockenschlohe** [comment]
Ich werde in den Quellcode ein paar Kommentare einfügen und das Issue schließen. :-)

**Comment by RetoLu** [comment]
Danke für die Schnelle Antwort.
Ich möchte diese Werten in den HomeAssistant übernehmen resp. mit diesem dann auch steuern, hast du Erfahrungen damit?
